
services:

  app:
    image: shinobisystems/shinobi:latest
    hostname: shinobi
    # container_name: shinobi
    restart: unless-stopped
    # network_mode: host
    ports:
      - 9016:8080
    environment:
      - TZ=America/Maceio
    volumes:
      - /srv/volumes/shinobi/config:/config
      - /srv/volumes/shinobi/customautoload:/customAutoLoad
      - /srv/volumes/shinobi/database:/var/lib/mysql
      - /srv/volumes/shinobi/videos:/opt/shinobi/videos
